source_dir = ".config/hooks/"

[commit-msg.commands.conventional-commit]
run = "uv run --script .config/hooks/commit_msg/commit_msg.py {1}"

[pre-commit]
parallel = true

[pre-commit.commands.prettier-formating]
run         = "echo {staged_files} | xargs npx prettier --ignore-unknown --write"
stage_fixed = true

[pre-commit.commands.prettier-formating.env]
NO_COLOR = "1"

[pre-commit.commands.ruff-lint-fmt]
glob        = "*.py"
run         = "uvx ruff check --fix {staged_files} && uvx ruff format"
stage_fixed = true
